# outputs.conf
# Defines where the logs collected by the forwarder should be sent.

[tcpout]
defaultGroup = default-autolb-group

[tcpout:default-autolb-group]
server = 192.168.56.1:9997   ; Host Machine running Splunk Enterprise

[tcpout-server://192.168.56.1:9997]
